### ISSUE TITLE
Can't get the ZIP working

### ISSUE THREAD

**Issue by gsueur** [davidread/ckanext-downloadall#19]
Hi David,
I may do something wrong, but I don't see what. Either from command line either from a backround job I can't get the "Download all" button activated and the zip file downloaded with the content. 
What should I type as the package name in the command line ? It seems that any typing gives me a success result  :
(default) root@ckan.dev.idgo.neogeo.fr:/usr/lib/ckan/default# downloadall -c /etc/ckan/default/production.ini update-zip TEST_FAKE
update-zip: SUCCESS

What am I doing wrong ? Thanks !

**Comment by davidread** [comment]
You need the package 'name' field, the same as if you were doing `package_show`. 

This is an example that hopefully should work (I've not tested it) or at least give you the idea:

Create a package in a shell:
```
paster --plugin=pylons shell /etc/ckan/default/development.ini
from ckan.tests import factories
factories.Sysadmin(name='admin', password='password')
org = factories.Organization(name='org', title='Test Org', image_url='')
factories.Dataset(name='test', title='Dataset1', owner_org=org['id'], resources=[{'url': 'https://raw.githubusercontent.com/datasets/gold-prices/master/data/annual.csv', 'format': 'csv'}])
```
As a test try downloading it using '-s' to do it synchronously:
```
(default) ubuntu@ubuntu-xenial:/vagrant/src/ckanext-downloadall$ downloadall update-zip test -s
```
And then in a second terminal run your background worker (assuming your not already running it with supervisord in the background):
```
paster --plugin=ckan jobs clear
paster --plugin=ckan jobs worker
```
and back in the first terminal do the load, but without '-s' and see the worker load it.

**Comment by ElrasDeVayne** [comment]
hi there!
I am also facing a problem in this regard.$

Ckan is installed in dockers and the connections between download-all Plugin and the ckan docker is working. However the downloadbutton doesn't download at all and it blocks the input of new datasets. To counter that i wrote in 
 `sudo emacs /var/lib/docker/volumes/docker_ckan_home/_data/venv/lib/python2.7/site-packages/ckanext/downloadall/helpers.py` 

```
def pop_zip_resource(pkg):
    '''Finds the zip resource in a package's resources, removes it from the                                                              
    package and returns it. NB the package doesn't have the zip resource in it                                                           
    any more.                                                                                                                            
    '''
    zip_res = None
    non_zip_resources = []
    try:
        f1=open("/tmp/log.txt","w")
        f1.write(str(pkg))
        f1.close()
        for res in pkg['resources']:
                if res.get('downloadall_metadata_modified'):
                        zip_res = res
                else:
                    non_zip_resources.append(res)
        pkg['resources'] = non_zip_resources
        return zip_res
    except:
        return None
```
With this the internal server error doesn't come and i can push data in the server. My question now is this a known problem that this ckan-extension has problems with the docker environment?

**Comment by davidread** [comment]
@ElrasDeVayne Can you try the example I give above and paste the full output please? Hopefully that will include the traceback of the exception and we can identify the problem.

**Comment by ElrasDeVayne** [comment]
Where should i do this input? in the DB docker or ckan docker?

Because when i do this input in the ckan container I get this.

syntax error near unexpected token `('

**Comment by davidread** [comment]
yes ckan container. I'm not sure why this bit of python is being rejected. what do you think the matter is?

**Comment by ElrasDeVayne** [comment]
Maybe something is wrong with the command? I tried it but I can't get it to work

**Comment by davidread** [comment]
@ElrasDeVayne It's hard to debug without more info. It's generally pretty torturous trying to solicit bits over a GitHub issue. Perhaps see if you can get some personal help with someone who has a better understanding of running these sorts of things.

**Comment by ElrasDeVayne** [comment]
I understand that. I got the system to work right now. I changed from Docker installation to a source one. The download button works now but when i press it failures follows. 

The link which is produces has a 5000 port. I changed it to a 8080 and it works. My question is right now is somewhere where i can change that?

**Comment by davidread** [comment]
@ElrasDeVayne Sorry for the delay - hopefully you worked it out in the end! I believe the link is generated from `ckan.site_url` config option.

I'll close this issue as it's got way off track. Raise a fresh issue if you think there is a problem with this repo.
