### ISSUE TITLE
KeyError 'resources' error using downloadall version 0.0.2

### ISSUE THREAD

**Issue by cesarjorgemartinez** [davidread/ckanext-downloadall#20]
Hi,

I have this error using downloadall version 0.0.2 (from pip):
KeyError 'resources'

Exists a 0.0.3 version to include the fix for this?

I'm using CKAN 2.7.6 by now.
Using master works, but I need to include in a pip version to automate better.

Regards,
Cesar Jorge

**Comment by davidread** [comment]
Thanks for the prompt. I've now done a 0.1.0 release. All the best with it!
